A1=int(input("Enter the First number to perform any operation please:"))
A2=int(input("Enter the Second number to start the operation please:"))
print("loading...........................................................")
print("......................................................................................................................"*5)
print("So the sum is:",A1 + A2)
print("and, the multiplcation of em's:",A1*A2)
print("and the floor division's result's:",A1//A2)
print("and the normal division's result's:",A1/A2)
print("and the Subtraction's result's:",A1-A2)
print("and finally the Remainder after dividing the given numbers:",A1%A2)